# -*- mode: ruby; coding: utf-8 -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "dummy"

  config.vm.provider :iijgp do |iijgp, override|
    iijgp.access_key = "YOUR ACCESS KEY"
    iijgp.secret_key = "YOUR SECRET KEY"
    iijgp.gp_service_code = "gpXXXXXXXX"
    iijgp.ssh_public_key = File.read("#{ENV['HOME']}/.ssh/id_rsa.pub")

    override.ssh.username = "root"
    override.ssh.private_key_path = "#{ENV['HOME']}/.ssh/id_rsa"
  end

  config.vm.define "vm1" do |c|
    c.vm.provider :iijgp do |iijgp|
      iijgp.gc_service_code = "gcXXXXXXXX"
      iijgp.label = "vagrant-iijgp test vm1"
    end
  end

  config.vm.define "vm2" do |c|
    c.vm.provider :iijgp do |iijgp|
      iijgp.gc_service_code = "gcYYYYYYYY"
      iijgp.label = "vagrant-iijgp test vm2"
    end
  end

  config.vm.define "another_gp_vm3" do |c|
    c.vm.provider :iijgp do |iijgp, override|
      iijgp.gp_service_code = "gpZZZZZZZZ"
      iijgp.gc_service_code = "gcZZZZZZZZ"
      iijgp.label = "vagrant-iijgp test vm3"
    end
  end
end
